- name: variables
  hosts: localhost
  vars:
    Course: "Terraform"
    Trainer: "Sivakumar"
    Duration: "20hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi I am learning {{Course}} from trainer {{Trainer}}, duration {{Duration}}."