- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Terraform') }}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: upper case
    ansible.builtin.debug:
      msg: " {{ greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greetings: "Hello, Good Morning"
  tasks: 
  - name: lower case
    ansible.builtin.debug:
      msg: "{{ greetings | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 2, 3, 4, 4, 5]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"             
            