- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Terraform') }}"

- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, Good Morning"
  tasks:
  - name: upper case
    ansible.builtin.debug:
      msg: " {{ greeting | upper }}"

- name: lower case
  hosts: localhost
  vars:
    greetings: "Hello, Good Morning"
  tasks: 
  - name: lower case
    ansible.builtin.debug:
      msg: "{{ greetings | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 2, 3, 4, 4, 5]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

- name: print min and max
  hosts: localhost
  vars: 
    ages: [25, 35, 45, 75]
  tasks:
  - name: print min and max
    ansible.builtin.debug:
      msg: "min age: {{ages | min}}, max age: {{ages | max}}"

- name: convert dictionary to item/list
  hosts: localhost
  vars:
    my_dict:
      Course: Ansible
      Trainer: Sivakumar
      Duration: 120hrs
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict}}"  
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_dict | dict2items }}"                                 

- name: convert items to dictionary
  hosts: localhost
  vars:
    my_list:
    - {'key': 'Course', 'value': 'Ansible'}
    - {'key': 'Trainer', 'value': 'Sivakumar'}
    - {'key': 'Duration', 'value': '120hrs'}
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_list}}"  
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_list | items2dict }}"                                 
              